---

- hosts: kubemaster
  remote_user: root
  gather_facts: yes
  pre_tasks:
  - name: 'Initialize Kubernetes'
    command: kubeadm init
    args:
      creates: /var/lib/kubelet/config.yaml
  - name: 'Check for tokens'
    shell: kubeadm token list | grep -v '^TOKEN' | wc -l
    register: num_tokens
  - name: 'Generate new token'
    command: kubeadm token create --print-join-command 
    args:
      creates: /root/kube_token
    register: kube_token
    when: num_tokens.stdout == "1"
  - name: 'Print kube_token'
    debug: 
      msg: "{{kube_token.stdout}}"
    when: num_tokens.stdout == "1"
  - name: 'Set kube_token fact'
    set_fact: kube_token="{{kube_token.stdout}}"
    when: num_tokens.stdout == "1"

- hosts: all
  remote_user: root
  gather_facts: yes
  tasks:
    - name: 'Join kubernetes cluster'
      command: "{{ hostvars[item].kube_token }}"
      args:
        creates: "/etc/kubernetes/kubelet.conf"
      when: hostvars[item].kube_token is defined
      with_items: "{{ groups['kubemaster'] }}"

- hosts: kubemaster
  remote_user: root
  gather_facts: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
    - name: Verify flannel is not enabled
      shell: kubectl get pods --all-namespaces | grep flannel | wc -l
      register: flannel_instances
    - name: Apply Flannel Config
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 
      when: flannel_instances.stdout == "0"
    - name: Copy kubeconfig to root
      command: cp /etc/kubernetes/admin.conf /root/.kube/config
      args:
        creates: /root/.kube/config
