---

- hosts: all
  remote_user: root
  gather_facts: no
  pre_tasks:
  - name: 'add hosts'
    copy:
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644
      src: files/hosts
  - name: 'disable selinux'
    selinux:
      state: disabled
  - name: 'enable br_netfilter'
    command: /usr/sbin/modprobe br_netfilter
  - name: 'setup nf-call-iptables bridge'
    command: echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables
  - name: 'disable swap'
    command: swapoff -a
